# 应用配置
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: gq
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd'T'HH:mm:ss

server:
  port: 8083

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
